# Generated by Django 3.1.6 on 2021-02-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotNo', models.IntegerField()),
                ('carNo', models.IntegerField(db_index=True, null=True)),
                ('isFree', models.BooleanField(default=True)),
            ],
        ),
    ]
