# Generated by Django 3.1.6 on 2021-02-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLotAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
